{ config, lib, pkgs, ... }:

let
  cfg = config.services.forgebot;

  # Default package from the flake
  defaultPackage = pkgs.forgebot or (throw "forgebot package not found in pkgs. Make sure the flake overlay is applied or set services.forgebot.package explicitly.");

  # Determine the actual secret values (read from files if paths provided, otherwise use literal values)
  webhookSecret = if cfg.secretTokens.webhookSecret != null
    then builtins.readFile cfg.secretTokens.webhookSecret
    else cfg.server.webhookSecret;

  forgejoToken = if cfg.secretTokens.forgejoPat != null
    then builtins.readFile cfg.secretTokens.forgejoPat
    else cfg.forgejo.token;

  # Generate the TOML content
  tomlContent = lib.concatStrings [
    "# Auto-generated by NixOS forgebot module\n"
    "# Do not edit manually - changes will be overwritten\n"
    "\n"
    "[server]\n"
    ''host = "${cfg.server.host}"''
    "\n"
    "port = ${toString cfg.server.port}\n"
    (lib.optionalString (webhookSecret != null) ''webhook_secret = "${webhookSecret}"'' + "\n")
    "\n"
    "[forgejo]\n"
    ''url = "${cfg.forgejo.url}"''
    "\n"
    (lib.optionalString (forgejoToken != null) ''token = "${forgejoToken}"'' + "\n")
    ''bot_username = "${cfg.forgejo.botUsername}"''
    "\n"
    "\n"
    "[opencode]\n"
    ''binary = "${cfg.opencode.binary}"''
    "\n"
    ''worktree_base = "${cfg.opencode.worktreeBase}"''
    "\n"
    ''config_dir = "${cfg.opencode.configDir}"''
    "\n"
    "\n"
    "[database]\n"
    ''path = "${cfg.database.path}"''
    "\n"
  ];

  # Script to write the TOML file
  writeTomlScript = pkgs.writeShellScript "forgebot-write-config" ''
    set -euo pipefail
    
    CONFIG_FILE="${cfg.configFilePath}"
    CONFIG_DIR="$(dirname "$CONFIG_FILE")"
    
    # Ensure the config directory exists with proper permissions
    mkdir -p "$CONFIG_DIR"
    chown ${cfg.user}:${cfg.group} "$CONFIG_DIR"
    chmod 0750 "$CONFIG_DIR"
    
    # Write the TOML configuration atomically
    cat > "$CONFIG_FILE.tmp" <<'TOML_EOF'
    ${tomlContent}TOML_EOF
    
    # Set restrictive permissions - only forgebot user can read
    chown ${cfg.user}:${cfg.group} "$CONFIG_FILE.tmp"
    chmod 0600 "$CONFIG_FILE.tmp"
    
    # Move atomically
    mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"
    
    # Verify the file was created successfully
    if [[ ! -f "$CONFIG_FILE" ]]; then
      echo "ERROR: Failed to create configuration file at $CONFIG_FILE" >&2
      exit 1
    fi
  '';
in
{
  options.services.forgebot = {
    enable = lib.mkEnableOption "forgebot daemon — a webhook bridge between Forgejo and opencode";

    package = lib.mkOption {
      type = lib.types.package;
      default = defaultPackage;
      defaultText = lib.literalExpression "pkgs.forgebot";
      description = "The forgebot package to use.";
    };

    # =============================================================================
    # Legacy option (for backward compatibility with warning)
    # =============================================================================
    configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = lib.literalExpression "/etc/secrets/forgebot.toml";
      description = "
        **DEPRECATED**: This option is deprecated and will be removed in a future version.
        Please migrate to using the structured options (`server`, `forgejo`, `opencode`, `database`)
        which auto-generate the configuration file. If set, this path will be used directly
        and the auto-generation will be skipped.
      ";
    };

    configFilePath = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/forgebot/forgebot.toml";
      description = "Path where the auto-generated forgebot.toml will be written.";
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/forgebot";
      description = "Directory where forgebot stores its data (database, worktrees, opencode config).";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "forgebot";
      description = "User account under which forgebot runs.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "forgebot";
      description = "Group under which forgebot runs.";
    };

    opencodePackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = pkgs.opencode or null;
      defaultText = lib.literalExpression "pkgs.opencode or null";
      description = "The opencode package to make available in the service PATH. If null, opencode must be available in the system PATH or configured with an absolute path in forgebot.toml.";
    };

    environment = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = lib.literalExpression ''
        {
          RUST_LOG = "debug";
          RUST_BACKTRACE = "1";
        }
      '';
      description = "Additional environment variables for the forgebot service.";
    };

    # =============================================================================
    # Server configuration
    # =============================================================================
    server = lib.mkOption {
      type = lib.types.submodule {
        options = {
          host = lib.mkOption {
            type = lib.types.str;
            default = "127.0.0.1";
            example = "0.0.0.0";
            description = ''
              The host address to bind the HTTP server to.
              Use "127.0.0.1" for localhost-only (with reverse proxy),
              or "0.0.0.0" to listen on all interfaces.
            '';
          };

          port = lib.mkOption {
            type = lib.types.port;
            default = 8765;
            example = 8080;
            description = ''
              The TCP port to listen on.
              Ports below 1024 require root privileges. Use 8080 or higher,
              or configure a reverse proxy for HTTPS.
            '';
          };

          webhookSecret = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            example = "your-webhook-secret-here";
            description = ''
              Webhook secret for HMAC signature verification.
              This MUST match the secret configured in Forgejo webhook settings.
              
              For production, it's recommended to use `secretTokens.webhookSecret`
              to read this from a file (e.g., sops-nix managed secret) instead of
              storing it directly in the Nix store.
              
              Either this option OR `secretTokens.webhookSecret` must be set.
            '';
          };
        };
      };
      default = { };
      description = "HTTP server configuration for the webhook receiver and setup UI.";
    };

    # =============================================================================
    # Forgejo integration
    # =============================================================================
    forgejo = lib.mkOption {
      type = lib.types.submodule {
        options = {
          url = lib.mkOption {
            type = lib.types.str;
            example = "https://git.example.com";
            description = ''
              The base URL of your Forgejo instance.
              Examples: "https://git.example.com", "http://localhost:3000", "https://codeberg.org"
            '';
          };

          token = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            example = "your-forgejo-api-token";
            description = ''
              API token for authenticating with Forgejo.
              
              For production, it's recommended to use `secretTokens.forgejoPat`
              to read this from a file (e.g., sops-nix managed secret) instead of
              storing it directly in the Nix store.
              
              Either this option OR `secretTokens.forgejoPat` must be set.
              To create a token: Forgejo Settings → Applications → Generate New Token
            '';
          };

          botUsername = lib.mkOption {
            type = lib.types.str;
            default = "forgebot";
            example = "forgebot";
            description = ''
              The username that forgebot will operate as.
              Used to identify bot comments, set git commit author, and filter self-triggered webhooks.
              The token must belong to this user.
            '';
          };
        };
      };
      description = "Forgejo integration settings for API access and webhook handling.";
    };

    # =============================================================================
    # opencode integration
    # =============================================================================
    opencode = lib.mkOption {
      type = lib.types.submodule {
        options = {
          binary = lib.mkOption {
            type = lib.types.str;
            default = "opencode";
            example = "/run/current-system/sw/bin/opencode";
            description = ''
              Path to the opencode binary.
              Use "opencode" to search in PATH, or an absolute path if opencode
              is not in the standard system PATH.
            '';
          };

          worktreeBase = lib.mkOption {
            type = lib.types.path;
            default = "/var/lib/forgebot/worktrees";
            example = "/var/lib/forgebot/worktrees";
            description = ''
              Base directory for git worktrees.
              forgebot creates a worktree for each issue inside this directory.
              Each worktree is an isolated checkout to prevent concurrent sessions
              from interfering with each other.
              
              Directory structure: <worktree_base>/<owner>_<repo>/<issue_number>/
            '';
          };

          configDir = lib.mkOption {
            type = lib.types.path;
            default = "/var/lib/forgebot/opencode-config";
            example = "/var/lib/forgebot/opencode-config";
            description = ''
              Directory for opencode configuration files.
              forgebot populates this with package.json, agent definitions, and tools.
              Do not modify these files manually — they are managed by forgebot.
            '';
          };
        };
      };
      default = { };
      description = "opencode agent integration settings.";
    };

    # =============================================================================
    # Database configuration
    # =============================================================================
    database = lib.mkOption {
      type = lib.types.submodule {
        options = {
          path = lib.mkOption {
            type = lib.types.path;
            default = "/var/lib/forgebot/forgebot.db";
            example = "/var/lib/forgebot/forgebot.db";
            description = ''
              Path to the SQLite database file.
              The database is created automatically on first run if it doesn't exist.
              Migrations run automatically on startup.
            '';
          };
        };
      };
      default = { };
      description = "SQLite database settings for persisting repository registrations and session state.";
    };

    # =============================================================================
    # Secret tokens (for sops-nix integration)
    # =============================================================================
    secretTokens = lib.mkOption {
      type = lib.types.submodule {
        options = {
          webhookSecret = lib.mkOption {
            type = lib.types.nullOr lib.types.path;
            default = null;
            example = lib.literalExpression "config.sops.secrets.forgebot-webhook-secret.path";
            description = ''
              Path to a file containing the webhook secret.
              When set, the secret is read from this file instead of using the
              literal value from `server.webhookSecret`.
              
              This enables integration with sops-nix or other secret management:
              `secretTokens.webhookSecret = config.sops.secrets.forgebot-webhook-secret.path`
            '';
          };

          forgejoPat = lib.mkOption {
            type = lib.types.nullOr lib.types.path;
            default = null;
            example = lib.literalExpression "config.sops.secrets.forgebot-token.path";
            description = ''
              Path to a file containing the Forgejo API token (PAT).
              When set, the token is read from this file instead of using the
              literal value from `forgejo.token`.
              
              This enables integration with sops-nix or other secret management:
              `secretTokens.forgejoPat = config.sops.secrets.forgebot-token.path`
            '';
          };
        };
      };
      default = { };
      description = ''
        Paths to secret files for sensitive configuration values.
        Use these options to integrate with sops-nix, agenix, or other
        secret management systems that provide secrets via files.
        
        When a secret token path is set, it takes precedence over the
        corresponding literal value option.
      '';
    };
  };

  config = lib.mkIf cfg.enable (
    let
      # Build the service PATH
      servicePath = lib.makeBinPath (
        [ cfg.package ]
        ++ lib.optional (cfg.opencodePackage != null) cfg.opencodePackage
      );

      # Determine the effective config file path
      effectiveConfigFile = if cfg.configFile != null
        then cfg.configFile
        else cfg.configFilePath;

      # Check if we're using auto-generated config or legacy configFile
      useAutoGeneratedConfig = cfg.configFile == null;
    in
    {
      # Warnings for deprecated options
      warnings = lib.optional (cfg.configFile != null) ''
        services.forgebot.configFile is deprecated. The NixOS module now auto-generates
        forgebot.toml from structured options. Please migrate to using:
          - services.forgebot.server.*
          - services.forgebot.forgejo.*
          - services.forgebot.opencode.*
          - services.forgebot.database.*
        See the documentation for examples.
      '';

      # Assertions to ensure required configuration is provided
      assertions = [
        {
          assertion = cfg.forgejo.url != null;
          message = "services.forgebot.forgejo.url must be set to your Forgejo instance URL (e.g., 'https://git.example.com')";
        }
        {
          assertion = (cfg.server.webhookSecret != null) || (cfg.secretTokens.webhookSecret != null);
          message = ''
            services.forgebot: Either server.webhookSecret or secretTokens.webhookSecret must be set.
            For production, use secretTokens.webhookSecret with a file path (e.g., sops-nix secret).
          '';
        }
        {
          assertion = (cfg.forgejo.token != null) || (cfg.secretTokens.forgejoPat != null);
          message = ''
            services.forgebot: Either forgejo.token or secretTokens.forgejoPat must be set.
            For production, use secretTokens.forgejoPat with a file path (e.g., sops-nix secret).
          '';
        }
      ];

      # Create the forgebot user
      users.users.${cfg.user} = {
        description = "Forgebot daemon user";
        isSystemUser = true;
        group = cfg.group;
        home = cfg.dataDir;
        createHome = true;
      };

      # Create the forgebot group
      users.groups.${cfg.group} = { };

      # Ensure data directory exists with correct permissions
      systemd.tmpfiles.rules = [
        "d '${cfg.dataDir}' 0755 ${cfg.user} ${cfg.group} -"
        "d '${cfg.opencode.worktreeBase}' 0755 ${cfg.user} ${cfg.group} -"
        "d '${cfg.opencode.configDir}' 0755 ${cfg.user} ${cfg.group} -"
      ];

      # Define the systemd service
      systemd.services.forgebot = {
        description = "Forgebot — Forgejo webhook bridge to opencode";
        wantedBy = [ "multi-user.target" ];
        after = [ "network-online.target" ];
        wants = [ "network-online.target" ];

        serviceConfig = {
          Type = "simple";

          # User and group
          User = cfg.user;
          Group = cfg.group;

          # Working directory (for relative paths in config)
          WorkingDirectory = cfg.dataDir;

          # State directory handling
          StateDirectory = "forgebot";
          StateDirectoryMode = "0755";
          CacheDirectory = "forgebot";
          CacheDirectoryMode = "0755";

          # Security hardening
          NoNewPrivileges = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          PrivateTmp = true;
          PrivateDevices = true;
          ProtectKernelTunables = true;
          ProtectKernelModules = true;
          ProtectControlGroups = true;
          RestrictSUIDSGID = true;
          RestrictRealtime = true;
          RestrictNamespaces = true;
          LockPersonality = true;
          MemoryDenyWriteExecute = true;

          # Allow writing to data directory
          ReadWritePaths = [ cfg.dataDir ];

          # Pre-start commands
          ExecStartPre = lib.mkMerge [
            # Verify legacy config file exists if using deprecated configFile option
            (lib.mkIf (!useAutoGeneratedConfig) [
              "${pkgs.coreutils}/bin/test -r ${lib.escapeShellArg cfg.configFile}"
            ])
            # Generate TOML configuration if using auto-generated config
            (lib.mkIf useAutoGeneratedConfig [
              "${pkgs.bash}/bin/bash ${writeTomlScript}"
            ])
          ];

          # Main service command
          ExecStart = "${cfg.package}/bin/forgebot --config ${lib.escapeShellArg effectiveConfigFile}";

          # Restart policy
          Restart = "on-failure";
          RestartSec = 10;
          StartLimitInterval = 60;
          StartLimitBurst = 3;

          # Environment variables
          Environment = [
            "PATH=${servicePath}:/run/current-system/sw/bin:/usr/bin:/bin"
            "RUST_LOG=info"
            "FORGEBOT_DATA_DIR=${cfg.dataDir}"
          ] ++ lib.mapAttrsToList (name: value: "${name}=${value}") cfg.environment;

          # Graceful shutdown
          TimeoutStopSec = 30;
          KillSignal = "SIGTERM";
        };
      };
    }
  );
}
